### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-barcode#1]
> As a GitHub repository, I should have some common data in order to get initialized.

## TASKS

- [x] Add the common project files, e.g. `README.md`, `LICENSE.md` ...
- [x] Add the dependencies and setup the `composer.json` file for the package.
- [x] Add a dummy service provider for the Laravel-Barcode service.
- [x] Add some dummy configuration for the Laravel-Barcode.
- [x] Add a test and use Travis-Ci for continous integration, don't forget that I will use Coveralls aswell.
