### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-barcode#1]
> As a GitHub repository, I should have some common data in order to get initialized.

## TASKS

- [x] Add the common project files, e.g. `changelog.md`, `license.md` ...
- [ ] Add the dependencies and setup the `composer.json` file for the package.
- [ ] Scaffold an empty service provider for the Laravel-Barcode service.
- [ ] Add the facade for the Laravel-Barcode service.
- [ ] Scaffold an empty configuration array for the Laravel-Barcode service.
- [ ] Add test case, tests and support for Travis-Ci continous integeration.
